# Generated by Django 5.0.6 on 2024-07-13 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymap', '0002_institution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ministry',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='ministry',
            old_name='lng',
            new_name='longitude',
        ),
    ]
